# Generated by Django 2.0.2 on 2018-09-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180926_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_stuff',
        ),
        migrations.AddField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
